version: "3"
services:
  app:
    build: "docker/go"
    container_name: go
    volumes:
      - ./src:/go/src/app:ro
    working_dir: /go/src/app
    command: "go run main.go"
    ports:
      - "3000:3000"